---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.checkpoint.dev
vagrant_ip: 10.10.10.10
vagrant_user: vagrant
vagrant_home: /home/vagrant
vagrant_webroot: /var/www/drupal

# Synced Folders
vagrant_synced_folders:
  - local_path: ~/Sites/checkpoint
    destination: /var/www
    id: drupal
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

ansible_os_family: Debian
#ansible_os_family: RedHat

# Server Extras
installed_extras:
  - drush
  - mailhogx
  - memcached
  - phpmyadmin
  - pimpmylog
  - solr
  - xdebug
  - xhprof
  - nodejs
  - varnish  
  # - checkpoint

# Additional Configuration
include_vars: config/apt.yml
include_vars: config/apache.yml
include_vars: config/drupal.yml
include_vars: config/firewall.yml
include_vars: config/nodejs.yml
include_vars: config/php.yml
include_vars: config/php_xdebug.yml
include_vars: config/pimpmylog.yml
include_vars: config/solr.yml
include_vars: config/varnish.yml  